### Punto 4 - Operaciones con Matrices

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# Matriz cuadrada 4x4

m1 = np.array([[2,4,6,3],[1,-2,7,1],[6,8,3,-2],[3,4,5,7]])
print(m1)
print('shape', m1.shape)

[[ 2  4  6  3]
 [ 1 -2  7  1]
 [ 6  8  3 -2]
 [ 3  4  5  7]]
shape (4, 4)


In [12]:
# Calculo determinante de la matriz
m1_det = np.linalg.det(m1)
m1_det

922.0000000000001

In [14]:
# Traza de la matriz
traza = np.trace(m1)
traza

10

In [16]:
# Rango de la matriz
rango = np.linalg.matrix_rank(m1)
rango

4

In [17]:
# valores de los coeficientes de su polinomio característico.
coef = np.poly(m1)
coef


array([  1., -10., -82., 515., 922.])

In [19]:
# Raices del polinomio
raices = np.roots(coef)
raices

array([12.82567889, -7.60135558,  6.28128222, -1.50560554])