### Actividad 5 - Punto 1

In [1]:
import numpy as np
from sklearn import datasets

#### 1.a

In [2]:
# Conjunto de datos de tres características linealmente relacionados
xa, ya = datasets.make_blobs(n_samples=100, centers=3, n_features=3, random_state=0)


In [3]:
# Imprimir los primeros 10 rows
print(xa[:10,:])

[[ 1.50876737 -2.40426734  1.29679476]
 [ 1.11992356 -1.09172105  2.87213416]
 [ 0.40675281  4.47917386  1.59276198]
 [ 0.60904044 -0.47892179  3.1678398 ]
 [ 1.52986507 -2.07655991  3.439008  ]
 [ 0.7856141   4.75242485  1.06283775]
 [-0.42878917  8.35744775 10.47051507]
 [ 0.79468751  5.71399196  1.68079583]
 [ 0.49685028  4.61515083  1.27924705]
 [ 0.94756207 -2.46243447  3.20526991]]


#### 1.b

In [4]:
# Conjunto de datos de cuatro características, relacionados de forma completa, no lineal.

xb,yb = datasets.make_classification(n_samples=100,
                             n_features=4,
                             n_repeated=0,
                             class_sep=0.1,
                             n_redundant=0,
                             random_state=0)


In [5]:
# Imprimir los primeros 10 rows
print(xb[:10,:])

[[-0.06154156  0.08842209  0.32964368  0.52389102]
 [-1.18978825 -0.89091508 -0.30374176  0.27451636]
 [ 0.6552506   0.35548179  0.33567148 -1.76853845]
 [-0.97156026  1.14110187 -0.68345655  0.85792392]
 [ 0.97834887 -0.24945858  0.89574591  0.84163126]
 [ 1.29390608  0.37005589 -0.21847932 -0.39944903]
 [ 0.42817583 -2.77259276 -0.68273822  0.39904635]
 [ 1.32234144  0.31721822 -1.15321581  0.91017891]
 [ 1.12899023 -1.02250684  0.14421447 -2.25556423]
 [ 2.75082392  0.7811981   0.11908932 -1.15618243]]


#### 1.c

In [6]:
# Conjunto de datos que, de manera prevista, puedan expresar una relación lineal.
# relacionados linealmente de 4 caracteristicas
xc, yc, coef = datasets.make_regression(
    n_samples=100,
    n_features=4,
    n_informative=1,
    noise=8.0,
    coef=True,
    random_state=0,
)

In [7]:
# Imprimir los primeros 10 rows
print(xc[:10,:])

[[-1.04525337  1.21114529  0.28634369  0.60884383]
 [-2.03068447  2.06449286  0.49374178 -0.11610394]
 [ 1.15233156  1.07961859 -0.30901297 -1.67600381]
 [ 0.15650654  0.23218104 -1.54079701  0.06326199]
 [-0.11816405 -0.6801782  -1.30652685  1.65813068]
 [ 0.52327666 -0.17154633 -0.03928282 -1.1680935 ]
 [ 0.39904635 -2.77259276 -0.31088617  0.09740017]
 [-0.36469354  0.15670386 -0.44092263 -0.2803555 ]
 [ 0.52106488 -0.57578797 -0.81336426 -1.46642433]
 [-0.68783761 -1.2140774   1.0685094  -0.4533858 ]]
