## Actividad 1

Operaciones con Matrices

### Punto 3

In [1]:
import numpy as np

In [16]:
# Genera una Matriz cuadrada de 4x4
A = np.array([[12,24,32,8],[15,7,21,4],[17,24,14,33],[10,9,13,27]])
A

array([[12, 24, 32,  8],
       [15,  7, 21,  4],
       [17, 24, 14, 33],
       [10,  9, 13, 27]])

In [20]:
# Calcula su inversa y su traspuesta.

A_inv = np.linalg.inv(A)
print('inversa', A_inv)

A_tra = A.transpose()
print('transpuesta', A_tra)


inversa [[-0.0596556   0.09368594  0.0570589  -0.06594233]
 [ 0.02690652 -0.03495285  0.04800465 -0.06146645]
 [ 0.03428659 -0.00358754 -0.05470138  0.05722974]
 [-0.00338253 -0.02132021 -0.01079677  0.05439388]]
transpuesta [[12 15 17 10]
 [24  7 24  9]
 [32 21 14 13]
 [ 8  4 33 27]]


In [21]:
# Multiplica la matriz por un escalar

mul_res = A * 2
mul_res

array([[24, 48, 64, 16],
       [30, 14, 42,  8],
       [34, 48, 28, 66],
       [20, 18, 26, 54]])

In [22]:
# Realiza el producto interno con una nueva matriz de dimensiones 4x2.

B = np.array([[2,3],[7,3],[6,4],[9,2]])

# producto interno
AB = A.dot(B)
AB


array([[456, 252],
       [241, 158],
       [583, 245],
       [404, 163]])