## Actividad 1

Solucion de sistemas de ecuaciones lineales

### Punto 5.a

In [1]:
import numpy as np

In [4]:
MCa = np.array([[1,2,5,-4],[5,8,1,1],[5,7,-3,2],[-1,3,9,-1]])
MSa = np.array([[21],[-8],[14],[5]])

print(MCa)
print(MSa)

[[ 1  2  5 -4]
 [ 5  8  1  1]
 [ 5  7 -3  2]
 [-1  3  9 -1]]
[[21]
 [-8]
 [14]
 [ 5]]


In [5]:
# Metodo 1

inv_MCa = np.linalg.inv(MCa)
solucion_m1 = inv_MCa.dot(MSa)
print('solucion metodo 1: ', solucion_m1)

solucion metodo 1:  [[-57.70175439]
 [ 41.31578947]
 [-22.66666667]
 [-27.35087719]]


In [6]:
# Metodo 2

solucion_m2 = np.linalg.solve(MCa, MSa)
print('solucion metodo2: ', solucion_m2)

solucion metodo2:  [[-57.70175439]
 [ 41.31578947]
 [-22.66666667]
 [-27.35087719]]


### Punto 5.b

In [8]:
MCb = np.array([[6,0,8],[2,2,1],[4,1,0]])
MSb = np.array([[9],[15],[-4]])

print(MCb)
print(MSb)

[[6 0 8]
 [2 2 1]
 [4 1 0]]
[[ 9]
 [15]
 [-4]]


In [9]:
# Metodo 1

inv_MCb = np.linalg.inv(MCb)
solucion_2m1 = inv_MCb.dot(MSb)
print('solucion metodo 1: ', solucion_2m1)

solucion metodo 1:  [[-3.24074074]
 [ 8.96296296]
 [ 3.55555556]]


In [10]:
# Metodo 2

solucion_2m2 = np.linalg.solve(MCb, MSb)
print('solucion metodo 2: ', solucion_2m2)

solucion metodo 2:  [[-3.24074074]
 [ 8.96296296]
 [ 3.55555556]]
