### Evidencia 1 - Punto 1 - Matematicas Computacionales

In [12]:
import numpy as np

#### a.

In [13]:
MC_a = np.array([[8,5,3,-6],[15,-3,4,7],[1,6,-2,1],[-2,1,7,-3]])
MS_a = np.array([[41],[13],[12],[0]])

print(MC_a)
print(MS_a)

[[ 8  5  3 -6]
 [15 -3  4  7]
 [ 1  6 -2  1]
 [-2  1  7 -3]]
[[41]
 [13]
 [12]
 [ 0]]


In [14]:
sol_a = np.linalg.solve(MC_a, MS_a)
print("Solucion del sistema de ecuaciones: ")
print(sol_a)

Solucion del sistema de ecuaciones: 
[[ 2.46143637]
 [ 1.79427813]
 [-0.55272084]
 [-2.33254682]]


#### b.

In [15]:
MC_b = np.array([[1,0,4],[5,3,2],[3,4,0]])
MS_b = np.array([[14],[25],[-12]])

print(MC_b)
print(MS_b)

[[1 0 4]
 [5 3 2]
 [3 4 0]]
[[ 14]
 [ 25]
 [-12]]


In [16]:
sol_b = np.linalg.solve(MC_b, MS_b)
print("Solucion del sistema de ecuaciones: ")
print(sol_b)

Solucion del sistema de ecuaciones: 
[[ 12. ]
 [-12. ]
 [  0.5]]
